//category
export const GET_TAGS = "GET_TAGS";
export const GET_TAGS_SUCCESS = "GET_TAGS_SUCCESS";
export const GET_TAGS_ERROR = "GET_TAGS_ERROR";
export const GET_TAG = "GET_TAG";
export const ADD_TAG = "ADD_TAG";
export const ADD_TAG_SUCCESS = "ADD_TAG_SUCCESS";
export const ADD_TAG_ERROR = "ADD_TAG_ERROR";
export const EDIT_TAG = "EDIT_TAG";
export const EDIT_TAG_SUCCESS = "EDIT_TAG_SUCCESS";
export const EDIT_TAG_ERROR = "EDIT_TAG_ERROR";
export const REMOVE_TAG = "REMOVE_TAG";
export const REMOVE_TAG_SUCCESS = "REMOVE_TAG_SUCCESS";
export const REMOVE_TAG_ERROR = "REMOVE_TAG_ERROR";
export const GET_CATE_COLLECTION = "GET_CATE_COLLECTION";
export const REFRESH = "REFRESH";

// Login
export const AUTH_LOGIN = "AUTH_LOGIN";

//Colecction
export const GET_COLLECTIONES = "GET_COLLECTION";
export const GET_COLLECTIONES_SUCCESS = "GET_COLLECTIONES_SUCCESS";
export const GET_COLLECTIONES_ERROR = "GET_COLLECTIONES_ERROR";
export const GET_COLLECTION = "GET_COLLECTION";
export const ADD_COLLECTION = "ADD_COLLECTION";
export const ADD_COLLECTION_SUCCESS = "ADD_COLLECTION_SUCCESS";
export const ADD_COLLECTION_ERROR = "ADD_COLLECTION_ERROR";
export const EDIT_COLLECTION = "EDIT_COLLECTION";
export const EDIT_COLLECTION_SUCCESS = "EDIT_COLLECTION_SUCCESS";
export const EDIT_COLLECTION_ERROR = "EDIT_COLLECTION_ERROR";
export const REMOVE_COLLECTION = "REMOVE_COLLECTION";
export const REMOVE_COLLECTION_SUCCESS = "REMOVE_COLLECTION_SUCCESS";
export const REMOVE_COLLECTION_ERROR = "REMOVE_COLLECTION_ERROR";

//Articales

export const GET_ARTICLES = "GET_ARTICLES";
export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";
export const GET_ARTICLES_ERROR = "GET_ARTICLES_ERROR";
// 
export const GET_ARTICLESV1 = "GET_ARTICLESV1";
export const GET_ARTICLESV1_SUCCESS = "GET_ARTICLESV1_SUCCESS";
export const GET_ARTICLESV1_ERROR = "GET_ARTICLESV1_ERROR";
// 
export const GET_ARTICLE = "GET_ARTICLE";
export const GET_ARTICLE_SUCCESS = "GET_ARTICLE_SUCCESS";
export const GET_ARTICLE_ERROR = "GET_ARTICLE_ERROR";
export const ADD_ARTICLE = "ADD_ARTICLE";
export const ADD_ARTICLE_SUCCESS = "ADD_ARTICLE_SUCCESS";
export const ADD_ARTICLE_ERROR = "ADD_ARTICLE_ERROR";
export const EDIT_ARTICLE = "EDIT_ARTICLE";
export const EDIT_ARTICLE_SUCCESS = "EDIT_ARTICLE_SUCCESS";
export const EDIT_ARTICLE_ERROR = "EDIT_ARTICLE_ERROR";
export const REMOVE_ARTICLE = "REMOVE_ARTICLE";
export const REMOVE_ARTICLE_SUCCESS = "REMOVE_ARTICLE_SUCCESS";
export const REMOVE_ARTICLE_ERROR = "REMOVE_ARTICLE_ERROR";
export const ADD_ARTICLE_VERSION = "ADD_ARTICLE_VERSION";
export const ADD_ARTICLE_VERSION_SUCCESS = "ADD_ARTICLE_VERSION_SUCCESS";
export const ADD_ARTICLE_VERSION_ERROR = "ADD_ARTICLE_VERSION_ERROR";
export const CLEAR_ARTICLE_ITEM = "CLEAR_ARTICLE_ITEM";

// update Articales
export const ADD_ARTICLE_VERIFY = "ADD_ARTICLE_VERIFY";
export const ADD_ARTICLE_VERIFY_SUCCESS = "ADD_ARTICLE_VERIFY_SUCCESS";
export const ADD_ARTICLE_VERIFY_ERROR = "ADD_ARTICLE_VERIFY_ERROR";
export const ADD_ARTICLE_REQUEST = "ADD_ARTICLE_REQUEST";
export const ADD_ARTICLE_REQUEST_SUCCESS = "ADD_ARTICLE_REQUEST_SUCCESS";
export const ADD_ARTICLE_REQUEST_ERROR = "ADD_ARTICLE_REQUEST_ERROR";
export const ADD_ARTICLE_REQUEST_V1 = "ADD_ARTICLE_REQUEST_V1";
export const ADD_ARTICLE_REQUEST_SUCCESS_V1 = "ADD_ARTICLE_REQUEST_SUCCESS_V1";
export const ADD_ARTICLE_REQUEST_ERROR_V1 = "ADD_ARTICLE_REQUEST_ERROR_V1";
//user

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_USER_INFO = "LOGIN_USER_INFO";
export const LOGOUT_USER = "LOGOUT_USER";
export const GET_USER_INFO = "GET_USER_INFO";
export const GET_USER_LIST = "GET_USER_LIST";

// pageUser

export const GET_USERS = "GET_COLLECTION";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";
export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_ERROR = "ADD_USER_ERROR";
export const EDIT_USER = "EDIT_USER";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_ERROR = "EDIT_USER_ERROR";
export const REMOVE_USER = "REMOVE_USER";
export const REMOVE_USER_SUCCESS = "REMOVE_USER_SUCCESS";
export const REMOVE_USER_ERROR = "REMOVE_USER_ERROR";
export const ACTIVE_USER = "ACTIVE_USER";
export const ACTIVE_USER_SUCCESS = "ACTIVE_USER_SUCCESS";
export const ACTIVE_USER_ERROR = "ACTIVE_USER_ERROR";
